### ISSUE TITLE
seL4 benchmarking 'Performance' page is broken

### ISSUE THREAD

**Issue by ljden** [seL4/website#131]
Navigating to the http://sel4.systems/About/Performance/ results in the following error message

> Content Encoding Error
The page you are trying to view cannot be shown because it uses an invalid or unsupported form of compression.
    Please contact the web site owners to inform them of this problem.

**Comment by lsf37** [comment]
Thanks for reporting this. It's due to the server being moved, which we are planning to do again very soon, so it might not make sense to fix it separately in the meantime. @wom-bat, I'll leave this one with you.

**Comment by lsf37** [comment]
The page is now back up, although not yet updated with the latest results. This will come in the next few weeks when hardware tests work again.

I'm closing this issue, since that bit is already tracked in seL4/ci-actions#75
