### ISSUE TITLE
Provide an anchor for each news item, so one can refer to them by a specific URL 

### ISSUE THREAD

**Issue by axel-h** [seL4/website#137]
https://sel4.systems/news.pml has a lot of news items now, sometime a need arises to link a specific item from the past. There seems no way to create an URL for this. My current case is linking to "13 August 2021: seL4 protects world's most secure drone from DEFCON hackers" together with a link to the presentation video now available at https://youtu.be/X9rsv4YIShY (we could add the link at the news item now). 

Creating a HTML anchor manually for each news item might be the most simple solution to solve this for now.  Creating an linkable anchor seems easy, just give the `div` tag a unique `id` made form the date-stamp
```
<div id="20210813" class="news-item">
  13 August 2021: seL4 protects world's most secure drone from DEFCON hackers
</div>
```
And then https://sel4.systems/news.pml#20210813 can be used. However, there is no easy way to make this link public, the crude way would be embedding a relative link:
```
<div id="20210813" class="news-item">
  13 August 2021: <a href="#20210813">seL4 protects world's most secure drone from DEFCON hackers</a>
</div>
```
or with an anchor symbol:
```
<div id="20210813" class="news-item">
  <a href="#20210813">&#9875;</a>&nbsp;
  13 August 2021: seL4 protects world's most secure drone from DEFCON hackers
</div>
```

**Comment by gernotheiser** [comment]
Thanks for doing this @axel-h , it has annoyed me too, but I didn't have the cycles to deal with it

**Comment by gernotheiser** [comment]
@wom-bat what do you think?

**Comment by lsf37** [comment]
We could make the date the link, i.e.
```html
<div id="20210813" class="news-item">
  <a href="#20210813">13 August 2021</a>: seL4 protects world's most secure drone from DEFCON hackers
</div>
```
Potentially giving it a class that has no decoration, or the anchor or another symbol as decoration. I like the idea of a symbol, but it would be good to not replicate it, so it remains consistently changeable. So something like
```html
<div id="20210813" class="news-item">
  <a href="#20210813" class="anchor">13 August 2021</a>: seL4 protects world's most secure drone from DEFCON hackers
</div>
```
with suitable CSS for class anchor.

**Comment by lsf37** [comment]
Tailwind uses a `#` on headers that pops up when you hover over the header, e.g. if you hover over `Focus` on [this page](https://tailwindcss.com/docs/hover-focus-and-other-states#focus). Might be a bit too subtle, but it could always show instead of only on hover.

**Comment by axel-h** [comment]
The hovering thing it no so uncommon, I was thinking about this also. But all that could be handled in CSS later also, if we use a dedicated class name.

**Comment by axel-h** [comment]
https://github.com/seL4/website/pull/138 will make this harder now, because we no longer have a single page to refer to.

**Comment by gernotheiser** [comment]
Good point. The page shouldn't get too long, but changing URLs is bad. Will rename main news page to avoid this

**Comment by gernotheiser** [comment]
#138 is replaced by #140 which provides stable links

**Comment by gernotheiser** [comment]
All news items have anchors now.
