### ISSUE TITLE
https://sel4.systems/Info/FAQ/proof.pml page doesn't talk about RISC-V

### ISSUE THREAD

**Issue by kent-mcleod** [seL4/website#143]
Under "What we prove":
" The binary code of the ARM version of the seL4 microkernel correctly implements the behaviour described in its abstract specification and nothing more. Furthermore, the specification and the seL4 binary satisfy the classic security properties called integrity and confidentiality. "

**Comment by lsf37** [comment]
And while we're at it, we should probably add access control for RISCV. Although if we wait a bit, we can include infoflow for RISCV as well.
