### ISSUE TITLE
Links are indistinguishable from regular text

### ISSUE THREAD

**Issue by xurtis** [seL4/website#31]
The link colour specified in the stylesheet is too dark, I can't easily tell where the links on a page are.

![steel 2020-10-09T1448 20](https://user-images.githubusercontent.com/2741168/95541225-8d4fcf00-0a3e-11eb-8505-24b30a737e3a.png)

https://github.com/seL4/website/blob/2e3e4ea5946148fda93caa9f10d8eb8cb3d5ac6d/content/css/sel4.css#L6

**Comment by lsf37** [comment]
Probably depends on the screen, it looked fine here, but that doesn't mean much. Would it make it more visible for you if it was one step lighter? Or better darker?

**Comment by lsf37** [comment]
I should probably add that the objective is *not* to make all links on a page stand out. They should mostly flow into the text, the main navigation links are buttons etc. But of course it still needs to be easily recognisable, otherwise there is no point.

**Comment by xurtis** [comment]
Either a fair bit lighter or indicated by something in addition to colour (potentially both). Closer to `#4060a0` would be easier to tell.

**Comment by xurtis** [comment]
Maybe as much as `#4070c0`

**Comment by lsf37** [comment]
Cool, thanks. Will have a look later.

**Comment by xurtis** [comment]
Might also need to adjust hover colour similarly (going darker on hover is strange)

**Comment by lsf37** [comment]
> Might also need to adjust hover colour similarly (going darker on hover is strange)

Pretty sure the darker-on-hover was a bootstrap default. But I'll experiment a bit.

**Comment by kent-mcleod** [comment]
There's some WCAG contrast guidelines here for some requirements that are standardized: https://www.w3.org/WAI/WCAG21/quickref/?currentsidebar=%23col_overview&showtechniques=1413%2C143#contrast-minimum

**Comment by lsf37** [comment]
New link colour implemented, so I'm closing this. Please re-open or open another issue if it is still a problem.
